# Generated by Django 5.0.1 on 2024-06-27 03:44

import facturacion.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apendice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=25, verbose_name='Nombre del campo')),
                ('etiqueta', models.TextField(max_length=50, verbose_name='Descripccion')),
                ('valor', models.CharField(max_length=150, verbose_name='Valor/Dato')),
            ],
            options={
                'verbose_name_plural': 'Apendices',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDomiciliado', models.CharField(choices=[('1', 'Domiciliado'), ('2', 'No Domiciliado')], max_length=25, verbose_name='Domicilio Fiscal')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total de la donacion')),
                ('totalLetras', models.CharField(max_length=200, verbose_name='Total en letras')),
                ('fechaTransmicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transmicion')),
                ('transmitido', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Comprobantes de Donaciones',
            },
        ),
        migrations.CreateModel(
            name='CuerpoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numItem', models.IntegerField(verbose_name='N° item')),
                ('tipoDonacion', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Bien'), ('3', 'Servicio')], max_length=20, verbose_name='Tipo de donacion')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigo', models.CharField(max_length=25, verbose_name='Codigo')),
                ('descripccion', models.CharField(max_length=1000, verbose_name='Descripccion')),
                ('depreciacion', models.IntegerField(verbose_name='Depreciacion')),
                ('montoDescu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('valorUni', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitario')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Donado')),
            ],
            options={
                'verbose_name_plural': 'Cuerpos del documento',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Codigo del departamento')),
                ('valor', models.CharField(max_length=100, verbose_name='Nombre del departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complementoDireccion', models.CharField(max_length=100, verbose_name='Direccion complemento')),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Codigo')),
                ('valor', models.CharField(max_length=50, verbose_name='Valores')),
            ],
            options={
                'verbose_name_plural': 'Formas de pago',
            },
        ),
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Version')),
                ('ambiente', models.CharField(choices=[('00', 'Modo Prueba'), ('01', 'Modo Produccion')], max_length=20, verbose_name='Ambiente de destino')),
                ('numeroControl', models.CharField(default=facturacion.models.generateNumeroControl, editable=False, max_length=31, verbose_name='Numero de control')),
                ('codigoGeneracion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipoModelo', models.CharField(choices=[('1', 'Modelo de Facturacion previo'), ('2', 'Modelo de Facturacion diferido')], max_length=50, verbose_name='Modelo de facturacion')),
                ('tipoOperacion', models.CharField(choices=[('1', 'Transmision normal'), ('2', 'Transmision por contingencia')], max_length=50, verbose_name='Tipo de Transmicion')),
                ('tipoContingencia', models.CharField(choices=[('1', 'No disponibilidad de sistema del MH'), ('2', 'No disponibilidad de sistema del emisor'), ('3', 'Falla en el suministro de servicio de Internet del Emisor'), ('4', 'Falla en el suministro de servicio de energia electrica del emisor que impida la transmision de los DTE'), ('5', 'Otro (debera digitar un maximo de 500 caracteres explicando el motivo)')], max_length=50, verbose_name='Tipo de Contingencia')),
                ('motivoContin', models.CharField(max_length=500, verbose_name='Motivo de Contingencia')),
                ('tipoMoneda', models.CharField(max_length=30, verbose_name='Tipo de Moneda')),
            ],
            options={
                'verbose_name_plural': 'Identificaciones',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Codigo del municipio')),
                ('valor', models.CharField(max_length=100, verbose_name='Nombre del municipio')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='OperacionesSujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numItem', models.IntegerField(verbose_name='N° item')),
                ('tipoItem', models.CharField(choices=[('1', 'Bienes'), ('2', 'Servicios'), ('3', 'Ambos (Bienes y servicios)'), ('4', 'Otros tributos por item')], max_length=25, verbose_name='Tipo de item')),
                ('codigo', models.CharField(max_length=25, null=True, verbose_name='Codigo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('montoDescu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ventas')),
                ('retencion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Retencion')),
                ('descripccion', models.TextField(max_length=1000, verbose_name='Descripccion')),
                ('precioUni', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.CreateModel(
            name='OtroDocumentoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codDocAsociado', models.CharField(choices=[('1', 'Emisor'), ('2', 'Receptor'), ('3', 'Medico'), ('4', 'Transporte')], max_length=25, verbose_name='Documento asociado')),
                ('descDocumento', models.CharField(max_length=100, verbose_name='Identificacion del documento asociado')),
                ('detalleDocumento', models.CharField(max_length=300, verbose_name='Descripccion de documento asociado')),
            ],
            options={
                'verbose_name_plural': 'Otros documentos asociados',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, verbose_name='Codigo')),
                ('montoPago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto por forma de pago')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia de la modalidad de pagos')),
                ('plazo', models.CharField(choices=[('01', 'Dias'), ('02', 'Meses'), ('03', 'Años')], max_length=20, verbose_name='Plazo')),
                ('periodo', models.IntegerField(verbose_name='Periodo de plazo')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='PagoDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo de Forma de pago')),
                ('montoPago', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto por Forma de pago')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia de la modalidad de pago')),
            ],
            options={
                'verbose_name_plural': 'Pagos de donacion',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Codigo del pais')),
                ('valor', models.CharField(max_length=100, verbose_name='Nombre del pais')),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('13', 'DUI'), ('36', 'NIT'), ('37', 'Otro'), ('03', 'Pasaporte'), ('02', 'Carnet de Residente')], max_length=25, verbose_name='Tipo de Documento')),
                ('homologado', models.CharField(choices=[('DUI', 'Documento Homologado'), ('NIT', 'Documento No Homologado')], max_length=30, verbose_name='Homologacion')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero del documento sin guion')),
                ('nrc', models.CharField(max_length=20, null=True, verbose_name='NRC')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre, Denominacion o Razon Social del contribuyente')),
                ('cellphone', models.CharField(help_text='Colocar el número sin identificador de país, sin espacios y sin guion.', max_length=30, verbose_name='Telefono movil del usuario')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electronico de la entidad')),
            ],
            options={
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='ResponseHacienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('datosJson', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='SujetoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCompra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total de operaciones')),
                ('descu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto global de Descuento, Bonificacion, Rebajas')),
                ('totalDescu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total del monto de Descuento, Bonificacion, Rebajas')),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('retencionIVAMH', models.CharField(choices=[('22', 'Retencion IVA 1%'), ('C4', 'Retencion IVA 13%'), ('C9', 'Otras retenciones IVA casos especiales')], max_length=30, verbose_name='Retencion IVA MH')),
                ('ivaRete1', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA Retenido')),
                ('reteRenta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rentencion de Renta')),
                ('totalPagar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total a Pagar')),
                ('totalLetras', models.CharField(max_length=200, verbose_name='Total en letras')),
                ('condicionOperacion', models.CharField(choices=[('1', 'Contado'), ('2', 'A credito'), ('3', 'Otro')], max_length=25, verbose_name='Condicion de la Operacion')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('fechaTransmicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transmicion')),
                ('transmitido', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Sujetos Excluidos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Codigo')),
                ('valores', models.CharField(max_length=50, verbose_name='Valores')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Codigo')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
    ]
