# Generated by Django 5.0.1 on 2024-12-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apendice',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='emisor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='apendice',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apendicesDonacion', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='comprobanteDonacion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cuerpoDocumentos', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cuerpos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='documento',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentoss', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='documentorelacionado',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacionados', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='extencion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extencion', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='emisor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='extencion',
            name='facturaElectronica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='facturaElectronica', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='documentorelacionado',
            name='facturaElectronica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentoRelacionado', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='documento',
            name='facturaElectronica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='apendice',
            name='facturaElectronica',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apendiceFacturaElectronica', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='facturaElectronica',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='medico',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='facturacion.departamento'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.municipio'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='otrodocumento',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='otros_documentos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='otrodocumento',
            name='facturaElectronica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='otroDocumento', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='otrodocumento',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.medico'),
        ),
        migrations.AddField(
            model_name='otrodocumentoasociado',
            name='comprobanteDonacion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='otrosDocumentos', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='otrodocumentoasociado',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.formapago'),
        ),
        migrations.AddField(
            model_name='pagodonacion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_donacion', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagodonacion'),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagofactura'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.pais'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='actividadEconomica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.actividadeconomica'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='direccionReceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.direccion'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor'),
        ),
        migrations.AddField(
            model_name='responsehacienda',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobanteDonacionResponse', to='facturacion.pagodonacion'),
        ),
        migrations.AddField(
            model_name='responsehacienda',
            name='facturaElectronica',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturaElectronicaResponse', to='facturacion.facturaelectronica'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='emisor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sujetosExcluidos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pago'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor'),
        ),
        migrations.AddField(
            model_name='responsehacienda',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujetoExcluidoResponse', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='sujetoExcluido',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='operacionesSujetoExcluido', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='apendice',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apendices', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='tipoDte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tributo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.tributo', verbose_name='facturas'),
        ),
        migrations.AddField(
            model_name='tributoresumen',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tributos_resumen', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='tributoresumen',
            name='tributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributos', to='facturacion.tributo'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='uniMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='documento',
            name='uniMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='uniMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='ventatercero',
            name='facturaElectronica',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ventaTercero', to='facturacion.facturaelectronica'),
        ),
    ]
