# Generated by Django 5.0.1 on 2024-06-27 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apendice',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='apendice',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apendicesDonacion', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='comprobanteDonacion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cuerpoDocumentos', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cuerpos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='identificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.identificador'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='facturacion.departamento'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.municipio'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='otrodocumentoasociado',
            name='comprobanteDonacion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='otrosDocumentos', to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='otrodocumentoasociado',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.formapago'),
        ),
        migrations.AddField(
            model_name='pagodonacion',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagodonacion'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.pais'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='actividadEconomica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.actividadeconomica'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='direccionReceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.direccion'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='receptores', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor'),
        ),
        migrations.AddField(
            model_name='responsehacienda',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='facturacion.pagodonacion'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='entidad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sujetosExcluidos', to='usuarios.entidad'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='identificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.identificador'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.pago'),
        ),
        migrations.AddField(
            model_name='sujetoexcluido',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.receptor'),
        ),
        migrations.AddField(
            model_name='responsehacienda',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='sujetoExcluido',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='operacionesSujetoExcluido', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='apendice',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apendices', to='facturacion.sujetoexcluido'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='tipoDte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='operacionessujetoexcluido',
            name='uniMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
        migrations.AddField(
            model_name='cuerpodocumento',
            name='uniMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
    ]
