# Generated by Django 5.0.1 on 2024-06-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Codigo del departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Codigo del municipio'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Codigo del pais'),
        ),
    ]
