# Generated by Django 5.0.1 on 2024-06-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_sujetoexcluido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Version'),
        ),
    ]
