# Generated by Django 5.0.1 on 2024-07-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_receptor_email'),
        ('usuarios', '0007_alter_customuser_entidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantedonacion',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='sujetoexcluido',
            name='identificador',
        ),
        migrations.AddField(
            model_name='comprobantedonacion',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='comprobanteDonacion',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.comprobantedonacion'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='sujetoExcluido',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.sujetoexcluido'),
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='fechaTransmicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Transmicion'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='emisor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='fechaTransmicion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Transmicion'),
        ),
    ]
