# Generated by Django 5.0.1 on 2024-07-16 21:15

import django.core.validators
import django.db.models.deletion
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_alter_apendice_comprobantedonacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='numItem',
            field=models.IntegerField(help_text='N° ítem, debe estar entre 1 y 2000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='N° item'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_code', message='El código debe ser un número del 01 al 14.', regex='^0[1-9]|1[0-4]$')], verbose_name='Codigo del departamento'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='complementoDireccion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Direccion complemento'),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='codigo',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_codigo', message='El código debe ser 01-14 o 99.', regex='^(0[1-9]|1[0-4]|99)$')], verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='motivoContin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo de Contingencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='tipoContingencia',
            field=models.CharField(blank=True, choices=[('', 'Seleccione opcion'), ('1', 'No disponibilidad de sistema del MH'), ('2', 'No disponibilidad de sistema del emisor'), ('3', 'Falla en el suministro de servicio de Internet del Emisor'), ('4', 'Falla en el suministro de servicio de energia electrica del emisor que impida la transmision de los DTE'), ('5', 'Otro (debera digitar un maximo de 500 caracteres explicando el motivo)')], default='', max_length=50, null=True, verbose_name='Tipo de Contingencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='tipoMoneda',
            field=models.CharField(default='USD', help_text='Tipo de Moneda', max_length=30, verbose_name='Tipo de Moneda'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='tipoOperacion',
            field=models.CharField(choices=[('1', 'Transmision normal'), ('2', 'Transmision por contingencia')], default='1', max_length=50, verbose_name='Tipo de Transmicion'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_code', message='El valor debe ser un número de exactamente dos dígitos.', regex='^^[0-9]{2}$')], verbose_name='Codigo del municipio'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, help_text='Cantidad debe ser mayor que 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[facturacion.models.validate_exclusive_min, facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='compra',
            field=models.DecimalField(decimal_places=8, help_text='Ventas. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Ventas'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='montoDescu',
            field=models.DecimalField(decimal_places=8, help_text='Descuento, Bonificación, Rebajas por ítem. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='numItem',
            field=models.IntegerField(help_text='N° ítem, debe estar entre 1 y 2000', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='N° item'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='precioUni',
            field=models.DecimalField(decimal_places=8, help_text='Precio Unitario debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='montoPago',
            field=models.DecimalField(decimal_places=2, help_text='Monto por forma de pago. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01.', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Monto por forma de pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodo de plazo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='plazo',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opccion'), ('01', 'Dias'), ('02', 'Meses'), ('03', 'Años')], default='', max_length=20, null=True, verbose_name='Plazo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia de la modalidad de pagos'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nombre',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nombre, Denominacion o Razon Social del contribuyente'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nrc',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_nrc', message='El nrc debe tener entre 1 y 8 dígitos.', regex='^[0-9]{1,8}$')], verbose_name='NRC'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='numero',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Numero del documento sin guion'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='descu',
            field=models.DecimalField(decimal_places=2, help_text='Monto global de Descuento, Bonificacion, Rebajas', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Monto global de Descuento, Bonificacion, Rebajas'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='ivaRete1',
            field=models.DecimalField(decimal_places=2, help_text='IVA Retenido. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='IVA Retenido'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pago'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='reteRenta',
            field=models.DecimalField(decimal_places=2, help_text='Retención Renta. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Rentencion de Renta'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='retencionIVAMH',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opccion'), ('22', 'Retencion IVA 1%'), ('C4', 'Retencion IVA 13%'), ('C9', 'Otras retenciones IVA casos especiales')], default='', max_length=30, null=True, verbose_name='Retencion IVA MH'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, help_text='Sub-Total. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='totalCompra',
            field=models.DecimalField(decimal_places=2, help_text='Total de Operaciones. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Total de operaciones'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='totalDescu',
            field=models.DecimalField(decimal_places=2, help_text='Total del monto de Descuento, Bonificación, Rebajas.', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Total del monto de Descuento, Bonificacion, Rebajas'),
        ),
        migrations.AlterField(
            model_name='sujetoexcluido',
            name='totalPagar',
            field=models.DecimalField(decimal_places=2, help_text='Total a Pagar. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.01', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of2], verbose_name='Total a Pagar'),
        ),
    ]
