# Generated by Django 5.0.1 on 2024-08-05 18:48

import django.core.validators
import django.db.models.deletion
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_remove_pago_codigo_alter_cuerpodocumento_numitem_and_more'),
        ('usuarios', '0008_alter_actividadeconomica_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpodocumento',
            name='montoDescu',
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='emisor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.entidad'),
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pagodonacion'),
        ),
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='valorTotal',
            field=models.DecimalField(decimal_places=8, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Total de la donacion'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='codigo',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='depreciacion',
            field=models.DecimalField(decimal_places=8, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Depreciacion'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Valor Donado'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='valorUni',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Valor Unitario'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='codigo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='pagodonacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Codigo de Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pagodonacion',
            name='montoPago',
            field=models.DecimalField(decimal_places=8, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Monto por Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pagodonacion',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia de la modalidad de pago'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='nrc',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_nrc', message='El nrc debe tener entre 1 y 8 dígitos.', regex='^[0-9]{1,8}$')], verbose_name='NRC'),
        ),
    ]
