# Generated by Django 5.0.1 on 2024-08-25 20:49

import django.core.validators
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_medico_tributo_alter_pagodonacion_entidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedonacion',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Total de la donacion'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='depreciacion',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Depreciacion'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1e-08), django.core.validators.MaxValueValidator(100000000000.0)]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ivaItem',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='IVA por Item'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='montoDescu',
            field=models.DecimalField(decimal_places=2, help_text='Descuento, Bonificación, Rebajas por ítem. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Descuento, Bonificacion, Rebajas por Item'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='noGravado',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(-100000000000.0), django.core.validators.MaxValueValidator(100000000000.0)], verbose_name='Cargos/Abonos que no afectan la base imponible'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='precioUni',
            field=models.DecimalField(decimal_places=2, help_text='Precio Unitario debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='psv',
            field=models.DecimalField(decimal_places=2, help_text='Precio Sujerido de Venta. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Precio Sujerido de Venta'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ventaExenta',
            field=models.DecimalField(decimal_places=2, help_text='Ventas Exentas. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Ventas Exentas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ventaGrabada',
            field=models.DecimalField(decimal_places=2, help_text='Ventas Gravadas. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Ventas Gravadas'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ventaNoSuj',
            field=models.DecimalField(decimal_places=2, help_text='Ventas no Sujetas. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Ventas no Sujetas'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad debe ser mayor que 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[facturacion.models.validate_exclusive_min, facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='compra',
            field=models.DecimalField(decimal_places=2, help_text='Ventas. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Ventas'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='montoDescu',
            field=models.DecimalField(decimal_places=2, help_text='Descuento, Bonificación, Rebajas por ítem. Debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='operacionessujetoexcluido',
            name='precioUni',
            field=models.DecimalField(decimal_places=2, help_text='Precio Unitario debe ser mayor o igual a 0, menor que 100000000000 y múltiplo de 0.00000001', max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='pagodonacion',
            name='montoPago',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0), facturacion.models.validate_exclusive_max, facturacion.models.validate_multiple_of], verbose_name='Monto por Forma de pago'),
        ),
    ]
