# Generated by Django 5.0.1 on 2024-08-27 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_alter_comprobantedonacion_valortotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuerpodocumento',
            name='codigo',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Codigo'),
        ),
    ]
