# Generated by Django 5.0.1 on 2024-06-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_entidad_actividadeconomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='actividadEconomica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.actividadeconomica'),
        ),
    ]
