# Generated by Django 5.0.1 on 2024-06-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_actividadeconomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entidad',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.entidad'),
        ),
    ]
