# Generated by Django 5.0.1 on 2024-07-01 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_entidad_direccionemisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.entidad'),
        ),
    ]
