# Generated by Django 5.0.1 on 2024-07-16 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_customuser_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='codigo',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_codigo', message='El el codigo debe tener entre 1 y 6 dígitos.', regex='^[0-9]{2,6}$')], verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='actividadeconomica',
            name='valor',
            field=models.CharField(max_length=150, verbose_name='Valores'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nrc',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nrc', message='El nrc debe tener entre 1 y 8 dígitos.', regex='^[0-9]{1,8}$')], verbose_name='NRC'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='codEstable',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Codigo del establecimiento asignado por el contribuyente'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='codEstableMH',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Codigo del establecimiento asignado por el MH'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='codPuntoVenta',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Codigo del punto de venta (Emisor) asignado por el Contribuyente'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='codPuntoVentaMH',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Codigo del punto de venta (Emisor) asignado por el MH'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nit',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nit', message='El nit debe tener exactamente 14 o 9 dígitos.', regex='^([0-9]{14}|[0-9]{9})$')], verbose_name='Numero de NIT sin guiones'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nrc',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_nrc', message='El nrc debe tener entre 1 y 8 dígitos.', regex='^[0-9]{1,8}$')], verbose_name='NRC'),
        ),
        migrations.AlterField(
            model_name='parametrosauthhacienda',
            name='nit',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nit', message='El nit debe tener exactamente 14 o 9 dígitos.', regex='^([0-9]{14}|[0-9]{9})$')], verbose_name='NIT'),
        ),
    ]
